// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alcrgiwkrqoxgecplgbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsY3JnaXdrcnFveGdlY3BsZ2JxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5ODU2NzIsImV4cCI6MjA2MzU2MTY3Mn0.yEFwTuGgSypF4yK80w-s0dJDV_A8k1Bq25gYNOkhfVw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);